
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://boltzmannbrain.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /lav-page
repository: BoltzmannBrain/boltzmannbrain.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Alexander Lavin"
title: "{ Alexander Lavin }"
description: "Personal website of Alexander Lavin; portfolio of projects; blogging on AI, tech, and random thoughts."
keywords: "Lavin, artifical intelligence, machine learning, Numenta, Vicarious"
favicon: "/img/level_up.ico"

################
# Header layout #
################

black-favicon: False

# background-img: "../img/intro-bg.png"
background-img: "../img/tedxcornelltech_02.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2500
lines: # You can add HTML Tags in the Text
  # - text: "Research engineer at Vicarious..."
  - text: "Brains and bits..."
  # - text: "Building machine intelligence from neuroscience"
  - text: "... bringing insights from neuroscience to AI."
  # - text: "... bringing insights from the brain to AI."
  # - text: "Check back soon for my portfolio :)"

me-img: "/img/8bit_linkedin.png"

##############################
# Color the browser elements #
##############################
color-browser: "#f9f9f9"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 30

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "boltzmannbrainblog"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/dojocat.jpg"
    date: "2014+"
    description: "AI ninja in training, currently with <a href='http://www.vicarious.com/' target='_blank'>Vicarious</a>, previously with <a href='http://www.numenta.com' target='_blank'>Numenta</a>"
  - image: "/img/timeline/robotocat.png"
    date: "2013-2014"
    description: "Carnegie Mellon, studied computational mechanics and worked on a <a href='http://lunar.xprize.org/teams/astrobotic' target='_blank'>lunar rover</a>"
  - image: "/img/timeline/octonaut.jpg"
    date: "2008-2012"
    description: "Cornell University, studied mechanical & aero engineering, with <a href='http://www.spacecraftresearch.com/flux/flux_overview.html' target='_blank'> cubesat research</a>"
  - image: "/img/timeline/welcometocat.jpg"
    date: "November 1989"
    description: "Hello world!"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "alexdlavin@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "Opinions are open source, feel free to fork them."
author_blurb: "\"Everything not saved will be lost.\"  - Nintendo quit screen message"
# author_blurb_image: "/img/linkedin.png"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/theAlexLavin"
  - title: "github"
    url: "https://github.com/BoltzmannBrain"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/alexander-lavin-b9644322"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  # Portfolio: 'portfolio'
  Timeline: 'timeline'
  Contact: 'contact'
  # Resume: 'resume'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
